//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMONIC_Session4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey
    {
        public int Id { get; set; }
        public Nullable<int> DepartureId { get; set; }
        public Nullable<int> ArrivalId { get; set; }
        public string Age { get; set; }
        public string Gender { get; set; }
        public Nullable<int> CabinTypeID { get; set; }
        public int Q1 { get; set; }
        public int Q2 { get; set; }
        public int Q3 { get; set; }
        public int Q4 { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Airports Airports { get; set; }
        public virtual Airports Airports1 { get; set; }
        public virtual Answer Answer { get; set; }
        public virtual Answer Answer1 { get; set; }
        public virtual Answer Answer2 { get; set; }
        public virtual Answer Answer3 { get; set; }
        public virtual CabinTypes CabinTypes { get; set; }
    }
}
